### ISSUE TITLE
Drop Radical.Extensions.Castle package

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/radical#132]
Actually the content of the Radical.Extensions.Castle assembly is only used by the Radical.Windows.Presentation.CastleWindsor assembly, we should merge them.

**Comment by mauroservienti** [comment]
How to self remove from package list?

**Comment by micdenny** [comment]
you can't permanently remove the package from nuget, you can unlist it:

- login to the [nuget.org](https://www.nuget.org) portal
- now go to the package
- then you will see a button `Delete Package` (as I said it is not a permanent deletion, and is explained in the next page)
- uncheck the List ...
- save
- done
- :smile:

**Comment by mauroservienti** [comment]
ok, those are the steps to remove it from the NuGet servers. The other question is: is there a way to remove it from the installed packages on the user machine?

Since we are merging it into another package already installed I fear that an update can cause conflicts because the same classes are now defined in different assemblies. Can we release an update that auto-remove it self from the installed packages  in the project?

I've found this: https://github.com/Particular/NServiceBus.Bootstrap.WindowsService/blob/master/packaging/nuget/install.ps1

that manually changes the packages.config file.

**Comment by micdenny** [comment]
As far as I saw the script is the way to accomplish those stuff but I never implemented one, I think it worth a try
