### ISSUE TITLE
Drag&Drop: Add Attached Property: OnDragOverCommand

### ISSUE THREAD

**Issue by nazarenomanco** [RadicalFx/radical#163]

**Comment by mauroservienti** [comment]
It already works as expected. There is no `drag over command`, what happens is that while the drag operation is on top something that in some way has the `drop command` the `CanExecute` of the `DropCommand` is called to get drag & drop feedback.

Until we have #154 you cannot use `AutoCommandBinding` to attach a command to a drag & drop operation if you need to add a drag over opinion.

The actual workaround is to create a full `ICommand` ad bind that to the DropCommand.
