### ISSUE TITLE
The validation logic/process is wrong

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/radical#167]
While implementing [support for `INotifyDataErrorInfo`](https://github.com/RadicalFx/radical/issues/124) emerged that the logic that the entire validation system runs when dealing with the old `IDataErrorInfo` implementation starts from a wrong assumption.

As a reference, I started from the [`INotifyDataErrorInfo` implementation](https://msdn.microsoft.com/en-us/library/system.componentmodel.inotifydataerrorinfo(v=vs.95).aspx) sample for Silverlight.

What is obvious from the above sample implementation is that when the UI requests the status of a property, using, in the sample, the `GetErrors` method, there is no validation involved. The reason for this is that the `INotifyDataErrorInfo` interface exposes an event to notify when the validation status changes.

The same approach is not actually used in the `IDataErrorInfo` implementation, where there is no notification mechanism, and where WPF calls the indexed property for each bound element at the first binding step and each time the property value changes. This forced us to introduce a check to skip the property validation the first the property is validated.

The wrong behavior is that we are validating properties each time WPF calls the indexed property.

### Proposed fix

* Define a set of tests, other than the ones already there, to define the behavior in both `ICanBeValidated` and `IRequireValidation` scenarios.

* Introduce a property `IsValidationEnabled` that detects if `ICanBeValidated`, `IRequireValidation`, `IDataErrorInfo` or `INotifyDataErrorInfo` are implemented;

* If `IsValidationEnabled` run validation on every property changed before calling the base property changed implementation, in this way we have the new validation status before WPF knows if the property is changed or not.

* stop validating properties each time WPF asks for the status of a property, simply returns the status of the property from the `ValidationErrors` collection.

* remove the logic behind `ValidationCalledOnceFor`

**Comment by micdenny** [comment]
:+1:
