### ISSUE TITLE
Throw a meaningful exception if the user tries to intercept a singleton `ViewModel` more than once 

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#175]
When using the `IViewResolver` the user can inject and interceptor action that will be invoked before the `ViewModel` is wired to the `View` to manipulate the `ViewModel`.

When dealing with singleton `ViewModel`s the above interceptor will be invoked only the first time, then is ignored. We should throw: https://github.com/RadicalFx/radical/blob/develop/src/net40/Radical.Windows.Presentation/Services/ViewResolver.cs#L110

**Comment by micdenny** [comment]
+1

**Comment by mauroservienti** [comment]
This issue was moved to RadicalFx/Radical.Windows.Presentation#2
