### ISSUE TITLE
Support nested/multiple properties validation

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#176]
Actually if the user implements `IRequireValidationCallback<TViewModel>` and during the custom validation process writes another property that triggers validation, the validation process blows up because the validation request is processed while another validation is in progress and the `PropertyValidationState` semaphore prevents it to happen.

The same happens if the user writes a property in a custom validation rule.

---

* related to #177
* #178 won't fix this.

**Comment by mauroservienti** [comment]
tests added.

**Comment by micdenny** [comment]
This issue should be moved under Radical.Windows.Presentation issue.

I temporary [Ignore] the unit tests to let the build server run successfully.

**Comment by mauroservienti** [comment]
This issue was moved to RadicalFx/Radical.Windows.Presentation#15
