### ISSUE TITLE
The Validated event is raised too early

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#177]
When a property validation occurs (`ValidateProperty`method) the `Validated` event is raised while the `PropertyValidationState` semaphore is still red.

The above means that if the user reacts to the `Validated` event touching other properties that require or trigger validation the validation process fails.

**Comment by micdenny** [comment]
This issue should be moved under Radical.Windows.Presentation issue and the TestCategory over the unit test should be updated with the new issue number.

**Comment by mauroservienti** [comment]
This issue was moved to RadicalFx/Radical.Windows.Presentation#14
