### ISSUE TITLE
Cascade changes for ObservableCollection

### ISSUE THREAD

**Issue by fabiocbr75** [RadicalFx/Radical#189]
it it possibile to get the same behavior of simple properties with the collection properties?

The following code is ok for simple properties but which is the way for cascade change notification on "add\delete" of observablecollection ?
this.GetPropertyMetadata( () => this.MyProperty ).AddCascadeChangeNotifications( () => this.AnotherProperty );

Thanks

**Comment by mauroservienti** [comment]
Yes it should be. Would be able to post a sample code usage. How would you like to use it, and what type of changes would like to monitor?


Sent by Outlook for Android





On Mon, Sep 14, 2015 at 12:47 PM -0700, "fabiocbr75" <notifications@github.com> wrote:












it it possibile to get the same behavior of simple properties with the collection properties?



The following code is ok for simple properties but which is the way for cascade change notification on "add\delete" of observablecollection ?

this.GetPropertyMetadata( () => this.MyProperty ).AddCascadeChangeNotifications( () => this.AnotherProperty );



Thanks

**Comment by fabiocbr75** [comment]
I'm sorry. There was a bug into my code. I changed the property value on another thread (non main thread). I changed my code with dispach invoker (application!!) and all work fine.
N.b. I like Radical :)

**Comment by mauroservienti** [comment]
> I'm sorry. There was a bug into my code. I changed the property value on another thread (non main thread). I changed my code with dispach invoker (application!!) and all work fine.

I'm glad that you solved the issue.

> N.b. I like Radical :)

Thanks :smile:
