### ISSUE TITLE
AutoCommandBinding

### ISSUE THREAD

**Issue by fabiocbr75** [RadicalFx/Radical#190]
With AutoCommandBinding the viewmodel is very clean but I don't found how is possibile convert following code in AutoCommandBinding way.

XXXCommand = DelegateCommand.Create()
                .OnExecute(o => MyFunc())
                .OnCanExecute(o => CanRun)
                .AddMonitor(PropertyObserver.For(this).Observe(v => v.prp1))
                .AddMonitor(PropertyObserver.For(this).Observe(v => v.prp2))
                .AddMonitor(NotifyCollectionChangedMonitor.For(this.MyObservableCollection));

Is it possible?

Thanks

**Comment by mauroservienti** [comment]
This issue was moved to RadicalFx/Radical.Windows#19
