### ISSUE TITLE
Introduce CallerMemberName in the property system

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#194]
Actually to write a `Radical` property the user needs to write the following:

```
public String MyProperty
{
   get{ return this.GetPropertyValue( () => MyProperty ); }
   set{ this.SetPropertyValue( () => MyProperty, value ); }
}
```

The `lambda expression` is required to pass in the property name in a compiler safe manner. Using `CallerMemberName` in the entity class we could allow the following syntax:

```
public String MyProperty
{
   get{ return this.GetPropertyValue<String>(); }
   set{ this.SetPropertyValue( value ); }
}
```

In the `get` we are unfortunately forced to explicitly use the generics signature because the type cannot be inferred.

`CallerMemberNameAttribute` is available starting with .NET 4.5, the effort required to introduce this is very low, what about the impact?

**Comment by micdenny** [comment]
+1

As far as we leave the backward compatibility leaving also the old style `get{ return this.GetPropertyValue( () => MyProperty ); }` I think it's a good thing to do.

**Comment by mauroservienti** [comment]
> backward compatibility

In my opinion backward compatibility is a must have, full stop.

**Comment by mauroservienti** [comment]
This seems to be not doable. If an entity is defined as follows:

```
class MyEntity : Entity
{
   public string MyProperty
   {
      get{ GetPropertyValue<string>(); }
      set{ SetPropertyValue<string>(value); }
   }
}
```

to enable the `CallerMemberName` attribute the base `Entity` type needs to use default values to make arguments optional:

https://github.com/RadicalFx/Radical/blob/14e38e2bc552dd5c8040fe45d13f73177a88212c/src/Radical/Model/Entity/Entity.cs#L364-L369

using default/optional arguments is a source of pain when the declared property is a `string`, as something like:

```
var m = new MyEntity();
m.MyProperty = "something"
```

makes so that "something" is interpreted as the property name.

I'm withdrawing this as the implications of doing it are more problematic of doing nothing.
