### ISSUE TITLE
PuzzleContainer add support for component release

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#20]
Call Dispose on disposable components at release time

**Comment by mauroservienti** [comment]
This introduces an interesting issue. @micdenny I need your opinion.

The MVVM toolkit relies for some behaviors on the fact that transient components when released (there is an automatic release mechanism in the conventions) if are also disposable components are disposed when released. I just tested it and Castle behaves exactly like that.

In order to introduce this behavior we must start to keep track of transient components in the container causing the container to hold a reference to created transient instance. This means that if you call Resolve 5 times the container will hold a reference to 5 instances so that when you call release the container can stop tracking the released one and can call dispose if required.

This means that it is also very easy to leak resources if not releasing them appropriately.

A potential approach could be to use in the container a weak reference to keep track of the transient instances.

thoughts?

**Comment by mauroservienti** [comment]
I just discovered that Unity has the exact same issue, disposable objects are not tracked thus not disposed at release time.

**Comment by mauroservienti** [comment]
And Autofac has no release support at all, so...who cares :)

**Comment by micdenny** [comment]
> In order to introduce this behavior we must start to keep track of transient components in the container causing the container to hold a reference to created transient instance.

I think a container should release/dispose transient object, and it surprise me that unity and autofac doesn't have this feature, but it's also true that injection is used to inject component that 90% of the time are singletons, otherwise a factory is injected. so yes probably who cares...

and also I think that probably we're going  to far with our container, it should be stupid simple, otherwise we should think to embed and hide a complete IoC container as castle in our binaries and use it as internal container, but this will add weight on our binaries, so probably I'm in favor of having a really keep it stupid simple container.

what I'm concerned about is disposing of View/ViewModel, this should be kept as is (don't remember the exactly pipeline right now)

**Comment by mauroservienti** [comment]
When a `View` is closed we invoke a convention called `ViewReleaseHandler` in order to release the `View` and its `ViewModel`, if any. By default on Castle this causes the invocation of the `Dispose` method if the object is `IDisposable`.
One thing we could do if the check, in he convention itself, if the object we are releasing is `IDisposable` and call `Dispose`.

thoughts?

**Comment by micdenny** [comment]
> One thing we could do if the check, in he convention itself, if the object we are releasing is IDisposable and call Dispose.

if it's not a PITA we could support that in our container.

**Comment by mauroservienti** [comment]
> if it's not a PITA we could support that in our container.

I think it's a PITA, we could end up in the same situation Castle is where if you don't release components you crate memory leaks, that is much worse, since the container now need to keep track of transient instances as well. More we'd end up in a scenario where we support containers that don't behave as we expect. Since the disposable pattern states that `Dispose` must be designed so that it can be called multiple times without side effects I'd say let's call `Dispose`.

**Comment by micdenny** [comment]
I think you should proceed with a PR (even a WIP PR) so I can better understand the solution you propose

**Comment by mauroservienti** [comment]
:+1:

**Comment by mauroservienti** [comment]
Fixed by https://github.com/RadicalFx/Radical.Windows.Presentation/issues/34
