### ISSUE TITLE
Add "ShouldHandle" behavior to broker 

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#239]
_From @melkio on February 23, 2017 9:24_

`IMessageBroker` doesn't support the possibility to add "filter" during subscription phase.

I'd like to have something like:

```
broker.Subscribe<T>( object subscriber, Predicate<object, T> shouldHandle, Action<object, T> callback );
```

to avoid filtering inside callback implementation

_Copied from original issue: RadicalFx/housekeeping#68_

**Comment by mauroservienti** [comment]
@melkio please take a look at https://github.com/RadicalFx/Radical/issues/242

**Comment by micdenny** [comment]
Wouldn't be interesting to implement Topic routing instead, something like [RabbitMQ.Topics](http://www.rabbitmq.com/tutorials/tutorial-five-dotnet.html)?

The topic is a list of words, delimited by dots. The words can be anything, but usually they specify some features connected to the message. A few valid examples: "stock.usd.nyse", "nyse.vmw", "quick.orange.rabbit".

When you subscribe you can specify the topic by using a routing key, that is in the same format of the topic, but has some special wildcard keys: 

\* (star) can substitute for exactly one word.
\# (hash) can substitute for zero or more words.

It's easiest to explain this in an example:

![image](https://cloud.githubusercontent.com/assets/1633595/23299042/51827fd0-fa80-11e6-8d15-945abc8ea97c.png)

**Does this make sense in Radical Message Broker?**

**Comment by mauroservienti** [comment]
Yes, it makes sense: https://github.com/RadicalFx/Radical/issues/6 😄 

The main intention of this PR is to introduce feature parity across the broker and the `IMessageHandler` interface. Message handlers allows you to filter incoming messages based on the message payload. It's content based filtering and not routing.
Topics on the other hand are routing, and I like it a lot.

**Comment by micdenny** [comment]
> Yes, it makes sense: #6 😄

ops, I repeated myself, sorry 😂 

> Message handlers allows you to filter incoming messages based on the message payload. It's content based filtering and not routing.

ok then, this make sense too, obviously! 😄  Probably with the Predicate approach we are just fine in Radical, and provides more control.
