### ISSUE TITLE
Switch between Views

### ISSUE THREAD

**Issue by danielearrighi** [RadicalFx/Radical#251]
Hello,
In my WPF application I have a loginView (with the LoginViewModel) as a starting view
`var bootstrapper = new WindsorApplicationBootstrapper<MyApp.Presentation.LoginView>();`

Then, when the user logs in successfully I close the login view and I open the MainView
`var mainView = _viewResolver.GetView<MainView>();
 mainView.Show();
//Closes the LoginView
_messageBroker.Broadcast(new CloseViewRequest(this));`

Likewise, in the Mainview I have a Logout button that closes the MainView and opens back (a fresh) LoginView
`var loginView = _viewResolver.GetView<LoginView>();
 loginView.Show();
//Closes the MainView
_messageBroker.Broadcast(new CloseViewRequest(this));`

But back in the LoginView when a new user logs in, I get a System.InvalidOperationException
`mainView.Show()` as I cannot set Visibility or call Show, ShowDialog etc.

If I Hide/Show the MainView this works well and I can Close and Reopen the Login View as many time I like.

Why this is happening? Is there a convention that the MainView cannot be reused?
Thank you for your help

Daniele

**Comment by mauroservienti** [comment]
Hi Daniele,

> Why this is happening?  Is there a convention that the MainView cannot be reused?

Somewhat 😄 the [`IsShellView`/`IsShellViewModel` convention](https://docs.radicalframework.com/mvvm/bootstrap-conventions.html) determines if the view (and its companion) is registered as `singleton` or as `transient` in the IoC container of choice. I [raised a PR](https://github.com/RadicalFx/documentation/pull/37) to clarify this in the aforementioned conventions documentation.

In your scenario when the `MainView` is closed is still tracked by the IoC container of choice and thus when re-opened WPF complains that a disposed object, or something like that, cannot be used anymore.

Simplest option in your scenario is probably to rename the `MainView` to something else that doesn't start with `Main*`, or to change the bootstrap conventions as follows:

```
var bootstrapper = new WindsorApplicationBootstrapper<Presentation.LoginView>()
                .OnBeforeInstall(bootConventions =>
                {
                    bootConventions.IsShellView = (services, implementation) =>
                    {
                        return services.Any(t => t.Name.IsLike("Main*"))
                            ? false
                            : bootConventions.DefaultIsShellView(services, implementation);
                    };

                    bootConventions.IsShellViewModel = (services, implementation) =>
                     {
                         return services.Any(t => t.Name.IsLike("Main*"))
                             ? false
                             : bootConventions.DefaultIsShellViewModel(services, implementation);
                     };
                });
```

**Comment by danielearrighi** [comment]
Works like a charm! Thank you!

**Comment by mauroservienti** [comment]
Super! glad to hear. Thanks for the feedback.
