### ISSUE TITLE
CastAs<T> extension can be obsoleted

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#317]

**Comment by nazarenomanco** [comment]
@mauroservienti I do not find it... I only found As<T> extension

**Comment by mauroservienti** [comment]
Wonderful!

**Comment by mauroservienti** [comment]
It's probably Cast and not CastAs

**Comment by nazarenomanco** [comment]
> It's probably Cast and not CastAs

I have found "As" and "CastTo" in CastExtensions. I think that's all.
