### ISSUE TITLE
Obsolete IRequireValidationCallback<T>

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/Radical#326]
- [x] Code: #409 
- [x]  Upgrade guide: https://github.com/RadicalFx/documentation/pull/147

**Comment by nazarenomanco** [comment]
@mauroservienti this interface is used on Validator.OnValidate

`            if (context.Entity is IRequireValidationCallback<T> irvc)
            {
                irvc.OnValidate(context);
            }`
What do we have to do?

**Comment by mauroservienti** [comment]
A of now, nothing. In v3 we'll drop that piece of code.

**Comment by mauroservienti** [comment]
Raised https://github.com/RadicalFx/documentation/pull/147
