### ISSUE TITLE
Radical & NET.CORE 3.1

### ISSUE THREAD

**Issue by Aurelio67** [RadicalFx/Radical#356]
Good morning mauro, you haven't heard from a life, I hope all is well there, in the future will it be possible to use radical with .NET CORE 3.1? I tried to create a project, but I noticed that the Radical.Window.Presentation (1.11.0) library is not compatible, it signals me an error when I insert AbstractViewModel and obviously also other features.
Fortunately for now everything works very well with the 4.8 framework, it is only a question to know if Radical can be used in the future.

Thanks as always for the excellent work done

Aurelio

Ps) Sorry for my not very good English (thank you google translator) :)

**Comment by mauroservienti** [comment]
@Aurelio67 good to hear from you! .NET Core support is coming 😄 

- Radical 2.0 is already .NET Standard 2 https://www.nuget.org/packages/Radical/2.0.0-Beta.6
- Radical Presentation has been merged into `Radical.Windows` and it's now available in beta for .NET Core 3: https://www.nuget.org/packages/Radical.Windows/2.0.0-Beta.8

There are still a few hiccups we're going through before being able to officially release 2.0.0. You can follow the progress by looking at the public project board: https://github.com/orgs/RadicalFx/projects/2?card_filter_query=milestone%3A2.0.0

**Comment by Aurelio67** [comment]
Miticooo!!!! as always, congratulations to the whole team

Grazieee
