### ISSUE TITLE
Info Radical con Xamari.Forms

### ISSUE THREAD

**Issue by Aurelio67** [RadicalFx/Radical#419]
Buongiorno Mauro & C, dovrei fare un mini progetto in Xamarin Form (Mvvm), sarebbe possibile utilizzare radical ?

Grazie 1000

Aurelio

**Comment by mauroservienti** [comment]
Al momento no @Aurelio67, abbiamo intenzione di approfondire (https://github.com/RadicalFx/Radical.Windows/issues/299) cosa si può fare in merito ma siamo tutti a digiuno 😄

**Comment by Aurelio67** [comment]
Hola Mauro, Ok

"ma siamo tutti a digiuno 😄" penso io a "foraggiarvi" col cibo 😄😄

Grazie 1000

Aurelio

**Comment by mauroservienti** [comment]
Non sono così sicuro che ti convenga 😆
Se sei interessato a seguire gli sviluppi sottoscrivi le notifiche a https://github.com/RadicalFx/Radical.Windows/issues/299.
